import logging
import pandas as pd
import numpy as np
import pandas_ta as ta
import yfinance as yf
from typing import Dict, Any, List

from python_bot.engine.brain.local_classifier import predict as local_ml_predict

# -------------------------------------------------------------------
# Configuration & Logging Setup
# -------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("BIST_QuantEngine_V2")

class AdvancedQuantBot:
    """
    Next-Generation Quantitative Trading Architecture for BIST 100
    
    Optimizations & Restructuring:
    1. Multi-Horizon Predictive Engines (Short, Medium, Long-Term algorithms).
    2. Advanced Feature Set (ADX, MACD, OBV, Bollinger Bands, ATR Trailing).
    3. Probabilistic Confidence Scoring instead of boolean flags.
    4. Dynamic Volatility-Adjusted Risk Management per Horizon.
    """

    # Model must clear this probability to fire a BUY signal. This is the one
    # remaining hand-set number in this class, but unlike the old 0.4/0.4/0.2
    # weight blend it gates a real model's own confidence rather than
    # combining several unrelated indicator point tallies into a score.
    ML_BUY_PROBABILITY_THRESHOLD = 0.55

    def __init__(self, symbol: str, start_date: str = "2020-01-01", end_date: str = None):
        self.symbol = symbol if symbol.endswith(".IS") else f"{symbol}.IS"
        self.fx_symbol = "USDTRY=X"
        self.start_date = start_date
        self.end_date = end_date
        self.df = pd.DataFrame()
        self.latest_usdtry_rate = None

    def fetch_data(self) -> pd.DataFrame:
        logger.info(f"Fetching dual-currency data for {self.symbol}...")
        equity_df = yf.download(self.symbol, start=self.start_date, end=self.end_date, progress=False)
        if isinstance(equity_df.columns, pd.MultiIndex):
            equity_df.columns = equity_df.columns.droplevel(1)
            
        fx_df = yf.download(self.fx_symbol, start=self.start_date, end=self.end_date, progress=False)
        if isinstance(fx_df.columns, pd.MultiIndex):
            fx_df.columns = fx_df.columns.droplevel(1)

        df = equity_df.join(fx_df['Close'].rename('USDTRY_Rate'), how='inner')
        df['USDTRY_Rate'] = df['USDTRY_Rate'].ffill()
        
        df['USD_Close'] = df['Close'] / df['USDTRY_Rate']
        self.latest_usdtry_rate = df['USDTRY_Rate'].iloc[-1]
        self.df = df.copy()
        return self.df

    def engineer_features(self) -> pd.DataFrame:
        logger.info("Engineering Multi-Horizon Volatility & Momentum Features...")
        df = self.df.copy()

        # 1. Trend & Baselines
        df.ta.ema(length=21, append=True)
        df.ta.sma(length=50, append=True)
        df.ta.sma(length=200, append=True)
        
        # 2. Momentum & Oscillators
        df.ta.rsi(length=14, append=True)
        df.ta.macd(fast=12, slow=26, signal=9, append=True)
        
        # 3. Volatility (Bollinger Bands & ATR)
        df.ta.bbands(length=20, std=2, append=True)
        df.ta.atr(length=14, append=True)
        
        # 4. Trend Strength & Volume
        df.ta.adx(length=14, append=True)
        df.ta.obv(append=True)
        df['OBV_EMA'] = df['OBV'].ewm(span=21).mean()

        # Fill NaNs generated by rolling windows
        self.df = df.bfill().ffill()
        return self.df

    def evaluate_horizons(self) -> pd.DataFrame:
        """
        Replaces the old hand-tuned indicator scoring matrix (a 0.4/0.4/0.2
        blend of three magic-number point tables across Short/Medium/Long
        horizons, per project audit) with a real prediction from the local
        scikit-learn classifier in engine/brain/local_classifier.py.

        That classifier is trained offline (see local_classifier.train_and_save)
        on RSI/EMA/SMA/volume features plus the HMM regime state, and predicts
        a single UP/DOWN/FLAT label with a probability for "as of today" (the
        most recent available bar) -- it does not retroactively re-score every
        historical bar in `self.df`, since re-fitting/re-predicting per bar
        would turn this lightweight signal into a full walk-forward backtest.
        So SIGNAL_BUY is only ever set on the latest row here; older rows in
        `self.df` keep their engineered indicator columns (still useful for
        ATR-based stop sizing in generate_risk_profile) but are not re-scored.
        """
        logger.info("Requesting local ML classifier prediction (replaces hand-tuned scoring)...")
        df = self.df

        df['ML_Predicted_Label'] = None
        df['ML_Probability'] = np.nan
        df['Composite_Score'] = 0.0
        df['SIGNAL_BUY'] = 0

        try:
            ml_result = local_ml_predict(self.symbol)
        except FileNotFoundError as e:
            logger.warning(f"No trained local ML model available ({e}); no signal will be generated. "
                            f"Run engine.brain.local_classifier.train_and_save([...]) first.")
            self.df = df
            return self.df

        predicted_label = ml_result["predicted_label"]
        probability = ml_result["probability"]

        last_idx = df.index[-1]
        df.loc[last_idx, 'ML_Predicted_Label'] = predicted_label
        df.loc[last_idx, 'ML_Probability'] = probability
        # Kept as a 0-100 display figure for existing consumers of
        # Composite_Score/Composite_Confidence; it is now a direct
        # reflection of the model's own probability, not a weighted blend.
        df.loc[last_idx, 'Composite_Score'] = probability * 100.0

        if predicted_label == "UP" and probability >= self.ML_BUY_PROBABILITY_THRESHOLD:
            df.loc[last_idx, 'SIGNAL_BUY'] = 1

        self.df = df
        return self.df

    def get_dynamic_usdtry_rate(self) -> float:
        if hasattr(self, '_cached_live_rate') and self._cached_live_rate is not None:
            return self._cached_live_rate
        try:
            live_rate = yf.download(self.fx_symbol, period="1d", interval="1m", progress=False)['Close'].iloc[-1]
            self._cached_live_rate = float(live_rate if not isinstance(live_rate, pd.Series) else live_rate.iloc[-1])
            return self._cached_live_rate
        except:
            return float(self.latest_usdtry_rate)

    def generate_risk_profile(self, row: pd.Series) -> Dict[str, Any]:
        """
        Dynamically adjusts Risk/Reward based on the local ML model's
        confidence for this signal (replaces the old three-horizon-score
        lookup, since the model now produces one probability, not three).
        """
        entry_try = row['Close']
        entry_usd = row['USD_Close']
        atr = row.filter(like='ATR').iloc[0]
        ml_probability = float(row.get('ML_Probability', 0.0) or 0.0)

        # Scale risk/reward and stop distance with model confidence: a more
        # confident prediction earns a wider (more patient) stop and target,
        # mirroring the old long-term/short-term split but driven by the
        # model's own probability rather than which hand-tuned score fired.
        horizon = "Moderate-Confidence (ML)"
        rr_multiplier = 2.0
        atr_multiplier_stop = 1.5

        if ml_probability >= 0.75:
            horizon = "High-Confidence (ML)"
            rr_multiplier = 3.0
            atr_multiplier_stop = 2.0  # Wider stop for high-conviction signals
        elif ml_probability < self.ML_BUY_PROBABILITY_THRESHOLD:
            horizon = "Low-Confidence (ML)"
            rr_multiplier = 1.5
            atr_multiplier_stop = 1.0  # Tighter stop when conviction is weak
            
        # Stop Loss in TRY
        stop_loss_try = entry_try - (atr_multiplier_stop * atr)
        
        # Dynamic Take Profit in USD (Protect against FX decay)
        usd_risk = (entry_try - stop_loss_try) / row['USDTRY_Rate']
        take_profit_usd = entry_usd + (usd_risk * rr_multiplier)
        
        # Convert Target back to TRY dynamically
        live_usdtry = self.get_dynamic_usdtry_rate()
        target_try_live = take_profit_usd * live_usdtry

        return {
            "Symbol": self.symbol,
            "Date": row.name.strftime('%Y-%m-%d'),
            "Horizon_Profile": horizon,
            "Composite_Confidence": f"{row['Composite_Score']:.1f}%",
            "Entry_TRY": round(entry_try, 2),
            "Stop_Loss_TRY": round(stop_loss_try, 2),
            "Target_USD": round(take_profit_usd, 3),
            "Live_USDTRY": round(live_usdtry, 4),
            "Target_TRY_LIVE": round(target_try_live, 2),
            "Projected_RR_Ratio": rr_multiplier
        }

    def run_pipeline(self) -> List[Dict]:
        self.fetch_data()
        self.engineer_features()
        self.evaluate_horizons()
        
        signals = self.df[self.df['SIGNAL_BUY'] == 1]
        logger.info(f"Optimized Pipeline Completed. Generated {len(signals)} high-probability orders.")
        
        orders = []
        for _, row in signals.iterrows():
            order = self.generate_risk_profile(row)
            orders.append(order)
            
        return orders

if __name__ == "__main__":
    bot = AdvancedQuantBot(symbol="THYAO", start_date="2022-01-01", end_date=None)
    orders = bot.run_pipeline()
    
    if orders:
        print("\n=== LATEST OPTIMIZED QUANTITATIVE ORDER ===")
        for k, v in orders[-1].items():
            print(f"{k}: {v}")

